Makefile
* Enable developers to run golangci linter from the command line
* Because it helps developers to catch mistakes before submit a pull-request
* Adding to the Makefile {{golangci-lint run}}
* Be able to run golangci-lint using {{make code/lint}}
=> [KEYCLOAK-11427] Add GolangCI linter to Keycloak Operator Makefile

Makefile
INTLY-3222
It seems Go 1.12 requires adding `-mod=vendor` flag.
=> INTLY-3222 Use vendor by default (Go 1.12)

.golangci.yml, test/e2e/keycloak_test.go
[KEYCLOAK-11505](https://issues.jboss.org/browse/KEYCLOAK-11505)
* Disable GolangCI rules for shadowing and and duplicates
* The work on the on the new Keycloak operator is based on scaffolding, which means that most of the code if fairly new and has to be refactored. Removing those rules will reduce the noise on PRs
* Changing GolangCI yaml file
* Have all the checks passing on GolangCI
* I had to run gofmt to fix the issues with e2e tests. To see what I mean, just run `make code/lint`
=> [KEYCLOAK-11505] Update GolangCI lint rules

pkg/common/cluster_actions.go, pkg/common/cluster_actions_test.go, pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_controller.go
None
Removing `context.TODO()` and adding context to the operator based on [this issue](https://github.com/keycloak/keycloak-operator/issues/23) opened by @philbrookes
All tests are passing
=> feat: Adding context to operator

.travis.yml, Makefile
* Included tasks into the Makefile to centralize everything in a single place
* `make/coverage` may overlap with `make/unit` so we might want to consider to merge then in a single command
* See: https://coveralls.io/github/abstractj/keycloak-operator
=> [KEYCLOAK-11498] Add Coveralls to CI

Makefile, go.mod
The command `make code/compile` will fail if project variable is not provided. In order to fix this, we just need to add the project name on top of the Makefile
I didn't create any Jiras because it's just a minor fix
=> Minor fix for Makefile

pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/keycloak_admin_secret.go, pkg/model/util.go
https://issues.jboss.org/browse/INTLY-3608
Adding keycloak admin username, password. Will also hold the url once the Ingress is in place.
1. Run operator locally and see secret is created and reconciled.
=> feat: Reconcile keycloak admin secret

cmd/manager/main.go, pkg/common/auto_detect.go, pkg/common/state_manager.go, pkg/controller/controller.go, pkg/controller/keycloak/keycloak_controller.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/controller/keycloakrealm/keycloakrealm_controller.go
https://issues.jboss.org/browse/INTLY-3768
Two changes in this PR.
1. Statemanagement has been refactored to limit access to one at a time, which takes into account multiple go routines accessing at the same time.
2. Autodetect has now been refactored to use a Go channel. The previous implementation was tied to a specific controller which would have meant a new autodetect instance per controller, checking for the same types of resources. Now the autodetect is setup once in the operator and sends events down the channel which the controller can listen too and setup a watch on the secondary resource.
1. Start the operator locally and check the logs to see the watch has been setup for the resources that exist on the cluster.
=> fix: Refactoring autodetect and statemanagement

pkg/model/database_secret.go, pkg/model/keycloak_admin_secret.go, pkg/model/keycloak_deployment.go, pkg/model/keycloak_discovery_service.go, pkg/model/keycloak_ingress.go, pkg/model/keycloak_route.go, pkg/model/keycloak_service.go, pkg/model/postgresql_deployment.go, pkg/model/postgresql_persistent_volume_claim.go, pkg/model/postgresql_service.go, pkg/model/rhsso_deployment.go, pkg/model/service_monitor.go
None
The label on the resources should be `app` instead of `application` for them to be grouped together. Otherwise, they will show up with all other resources in a namespace.
**Old:**
**New:**
None required
=> fix: Change application label to app

deploy/role.yaml
None
Updating the role permissions to allow the operator to work correctly when deployed into a namespace
1. Run `make cluster/prepare`
2. Modify `operator.yaml` image to `quay.io/davidffrench/keycloak-operator:INTLY-3732`
3. Run `kubectl apply -f deploy/operator.yaml`
4. Run `kubectl apply -f deploy/examples/keycloak/keycloak.yaml
5. Ensure everything is deployed successfully
=> fix: Updating role permissions

.golangci.yml
GolangCI is complaining about some of our TODOs like https://golangci.com/r/github.com/keycloak/keycloak-operator/pulls/46. I believe this just adds unnecessary noise to our PRs and should be disabled.
=> Disable godox to stop the noise from GolangCI about our TODOs

deploy/cluster_roles/cluster_role.yaml, deploy/cluster_roles/cluster_role_binding.yaml, deploy/examples/keycloak/rhsso.yaml
Adding cluster roles (needed for multi namespace support).
To try out multi namespace support, first create the cluster roles:
```sh
$ oc apply -f deploy/cluster_roles
```
The modify `operator.yaml` and set an empty watch namespace...
```yaml
...
env:
- name: WATCH_NAMESPACE
value: ''
...
```
...and deploy it.
=> add cluster roles

deploy/crds/Keycloak.yaml, deploy/crds/KeycloakRealm.yaml
None
Unfortunately, the changes introduced in https://github.com/keycloak/keycloak-operator/pull/55 need to be reverted as it breaks compatibility with Kubernetes 1.11 which we need to support due to OpenShift 3.11
None needed
=> Revert pruning commits

pkg/model/constants.go, pkg/model/keycloak_deployment.go, pkg/model/rhsso_deployment.go, pkg/model/util.go
https://issues.jboss.org/browse/INTLY-3373
Use a persistent tag in the case of Keycloak and RH-SSO which negates the need for an imagestream. Also, allow the patch version to be updated without the operator reconciling back. This is to allow for CVE updates on a production cluster.
1. Create new keycloak instance using this branch
2. Modify the keycloak statefulset image to version '7.0.0' and the replicas to 3.
3. Confirm that the image version stays the same and the replicas change back to 1
4. Modify the keycloak statefulset image to version '8.0.0' 
5. Confirm the version changes back to `7.0.0`
6. Repeat steps 1-5 for rhsso
=> feat: Allow user changes to keycloak image

pkg/model/prometheus_rule.go
https://issues.jboss.org/browse/INTLY-3774
The KeycloakAPIRequestDuration99PercThresholdExceeded alerts is checking that 99.5% of requests are being served within 10 seconds over a period of 5 minutes, but the alert name states that this percentage is 99%:
None required. it is just a name change
=> fix: Update PromRule name to reflect query

deploy/cluster_roles/cluster_role.yaml, deploy/role.yaml
None
Operator is broken without this change. Using the operator on the cluster was not working due to missing permissions for jobs, cronjobs and keycloakbackups in the role
1. Run the operator from an image in the cluster using the rbac applied from this branch.
=> fix: Adding permissions for cronjobs and jobs

deploy/crds/KeycloakBackup.yaml
None
Removing type filed from KeycloakBackup CRD so it can be applied to Kubernetes 1.11
=> fix: Remove structural schema from CRD

pkg/model/keycloak_deployment.go, pkg/model/keycloak_deployment_test.go, pkg/model/rhsso_deployment.go, pkg/model/rhsso_deployment_test.go, pkg/model/util.go, pkg/model/util_test.go
Follow on from https://github.com/keycloak/keycloak-operator/pull/64
https://issues.jboss.org/browse/INTLY-3373
Adding additional logic based on an excellent observation from @slaskawi that would mean operator upgrades with a new operand version would not take effect.
1. Create new keycloak instance using this branch
2. Modify the keycloak statefulset image to version '7.0.0' and the replicas to 3.
3. Confirm that the image version stays the same and the replicas change back to 1
4. Modify the keycloak statefulset image to version '8.0.0'
5. Confirm the version changes back to 7.0.0
6. Repeat steps 1-5 for rhsso
=> fix: Additional logic to correctly check version updates

pkg/controller/keycloak/keycloak_controller.go
Before this change, there were cases where nanoseconds were used.
=> Make requeue constants actually seconds

pkg/common/user_state.go
Fixes an error where the operator tried to read the roles even if the user could not be found.
=> fix user not found error

pkg/common/cluster_actions.go
Bugfix: the realm override for a browser redirect used the wrong property for setting the default provider.
=> fix realm overrides

pkg/model/constants.go
[KEYCLOAK-12259](https://issues.jboss.org/browse/KEYCLOAK-12259)
Based on a mail thread, Postgres should be updated to 10.1 but this is not working with OpenShift due to permissions. It is working with 11.5 but we need confirmation we can upgrade to this.
1. Create Keycloak instance from this branch
2. Run any other tests you think are required.
=> feat: Upgrade Postgres to 11.5

deploy/crds/keycloak.org_keycloakbackups_crd.yaml, deploy/crds/keycloak.org_keycloakclients_crd.yaml, deploy/crds/keycloak.org_keycloakrealms_crd.yaml, deploy/crds/keycloak.org_keycloaks_crd.yaml, deploy/crds/keycloak.org_keycloakusers_crd.yaml, docs/external-database.asciidoc, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/keycloakbackup_types.go, pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/keycloakuser_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
[KEYCLOAK-12231](https://issues.jboss.org/browse/KEYCLOAK-12231)
This Pull Request adds a lot of documentation to the Go objects and CRDs. Note, that once comments are added to the code, we need to regenerate both Open API and K8s objects by invoking:
```
operator-sdk-local generate k8s
operator-sdk-local generate openapi
```
=> KEYCLOAK-12231 Add description to all the fields

Dockerfile
[KEYCLOAK-12408](https://issues.redhat.com/browse/KEYCLOAK-12408)
Here's an output from Skopeo:
```
$ skopeo inspect docker://registry.access.redhat.com/ubi8/ubi-minimal
{
"Name": "registry.access.redhat.com/ubi8/ubi-minimal",
"Digest": "sha256:32fb8bae553bfba2891f535fa9238f79aafefb7eff603789ba8920f505654607",
"RepoTags": [
"8.1",
"8.0",
"8.0-204",
"8.0-213",
"8.0-159",
"8.0-127",
"8.1-279",
"latest",
"8.0-131"
],
"Created": "2019-10-29T16:44:32.524013Z",
"DockerVersion": "1.13.1",
"Labels": {
"architecture": "x86_64",
"authoritative-source-url": "registry.access.redhat.com",
"build-date": "2019-10-29T16:44:07.247612",
"com.redhat.build-host": "cpt-1006.osbs.prod.upshift.rdu2.redhat.com",
"com.redhat.component": "ubi8-minimal-container",
"com.redhat.license_terms": …
```
=> KEYCLOAK-12408 Lock UBI Image version

pkg/model/prometheus_rule.go
None
The alerts for KeycloakInstanceNotAvailable and KeycloakDatabaseNotAvailable alerts have been broken for a while. These PR updates them to use the correct labels
1. Install application monitoring stack
2. Install this operator
3. Verify alerts are green
=> fix: Update broken monitoring alerts

pkg/controller/keycloak/keycloak_controller.go, test/e2e/keycloak_test.go, test/e2e/utils.go
KEYCLOAK-12449
The operator failed to sync CRs into its keycloak cluster using the
service since it used http and the service's IP on keycloak's SSL port.
This is a blocker - especially in non-openshift clusters without Route
CRD support.
This PR makes the operator use https and the service's name instead.
see https://issues.redhat.com/browse/KEYCLOAK-12449
=> KEYCLOAK-12449: Fix internal keycloak URL.

pkg/common/controller_utils.go, pkg/controller/keycloakrealm/keycloakrealm_reconciler.go, pkg/controller/keycloakrealm/keycloakrealm_reconciler_test.go, pkg/controller/keycloakuser/keycloakuser_reconciler.go
https://issues.redhat.com/browse/KEYCLOAK-12841
If no credentials are provided when creating users, the operator should not assign random ones. There are legitimate use cases where users without credentials are needed.
1. Deploy Keycloak from this branch
2. Create a realm
3. Create a user in the realm
4. Check the user output secret: it should only contain a username but no password
5. Login to the admin console and check the user: in the credential section there should be no 'Disable credentials' section
Note that once credentials are assigned to a user, it is not possible to remove them via the CR. Keycloak ignores an update with removed credentials.
=> KEYCLOAK-12841: allow creating users without credentials

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, pkg/controller/keycloakrealm/keycloakrealm_reconciler_test.go
https://issues.redhat.com/browse/INTLY-4404 (converted to Keycloak JIRA)
https://issues.redhat.com/browse/KEYCLOAK-12807
Enable audit logging by default for realms created by the operator. This will enable recording of Admin Events, Login Events and JSON representations for Admin Events.
The list of events will look like this:
1. Deploy keycloak using the operator from this branch
1. Create a realm and don't specify any additional parameters in the CR
1. Open the realm in the admin console and navigate to `Events > Config`
1. Both Login and Admin Events should be enabled and Include Representation should be enabled for Admin Events.
=> KEYCLOAK-12807 add options for audit logging

Makefile, pkg/model/keycloak_deployment.go, pkg/model/rhsso_deployment.go
https://issues.redhat.com/browse/KEYCLOAK-12766
*What:*
Adding X509_CA_BUNDLE env var for Keycloak/SSO deployment.
Small fix in Makefile - operator SDK version set to same version as in go.mod
*Why:*
To fix issue on a cluster with a self signed certificate.
*How:*
This approach for a fix was discussed on a [mailing list thread](https://groups.google.com/d/topic/keycloak-dev/WCpPV6hSB6Y/discussion).
Install on a Openshift 4 cluster with self signed certificate for OpenShift API route.
Setup your cluster as an IDP in Keycloak.
Add a test app that will use Keycloak for authentication.
Test authentication with OpenShift 4 IDP - login should succeed
=> KEYCLOAK-12766 add X509_CA_BUNDLE env var

deploy/role.yaml
Adding delte permission to the endpoint apiGroup so that Keycloak Operator does not fail when setting ownerRef while creating an external database endpoint
When enabling external database, the Operator fails with the following error message: -
```
endpoints “keycloak-postgresql” is forbidden: cannot set an ownerRef on a
resource you can’t delete: , <nil>
```
=> Adding delete permission to the endpoint apiGroup

deploy/cluster_roles/cluster_role.yaml
@slaskawi as requested I've created a ticket. Due to lack of knowledge how I can change my existing pull requested I've decided to create a new one.
For the completeness here also the text of the ticket:
We tried to test the Keycloak-operator on cluster level. Therefore as documented within the code we changed the WATCH_NAMESPACE variable to be empty.
```
env:
- name: WATCH_NAMESPACE
- name: POD_NAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: metadata.name
```
which resulted into the following errors.
```
E0131 14:02:51.608725       1 reflector.go:125] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.PodMonitor: podmonitors.monitoring.coreos.com is forbidden: User "system:serviceaccount:keycloak:keycloak-operator" cannot list resource …
```
=> KEYCLOAK-12915: Add missing rights to be able to run on clusterscope

deploy/operator.yaml, pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/constants.go, pkg/model/keycloak_deployment.go, pkg/model/keycloak_probes.go, pkg/model/rhsso_deployment.go, test/e2e/constants.go
[KEYCLOAK-10708](https://issues.redhat.com/browse/KEYCLOAK-10708)
This Pull Request introduces better Liveness and Readiness checks to both, Keycloak and RHSSO deployments.
When creating all necessary objects, the Operator creates now `keycloak-probes` ConfigMap with both `readiness_probe.sh` and `liveness_probe.sh` files. Those files are not being updated by the Operator, so they might be tweaked manually (if necessary).
Probes timeouts have also been slightly increased to make it more tolerant.
=> KEYCLOAK-10708 Better readiness/liveness checks

pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_migrations_test.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/constants.go, pkg/model/keycloak_deployment.go, pkg/model/postgresql_service.go, pkg/model/rhsso_deployment.go, pkg/model/util.go, pkg/model/util_test.go
https://issues.redhat.com/browse/KEYCLOAK-12929
ping @davidffrench 
The Keycloak Operator allows connecting to external (outside of the cluster) databases by providing a pre-populated database secret. This only worked when specifying the IP Address of the external database. This is a problem because the IP address can change. We want to support both, IP and hostname.
Unfortunately IP adresses and hostnames have to be treated in different ways: Hostnames are supported by externalName type services. But this type of service does not support IP addresses and so we have to rely on default ClusterIP type services and an Endpoints object to support that use case. This PR checks if the pre-existing database secret contains an IP or a hostname and chooses the reconciliation strategy accordingly. …
=> KEYCLOAK-12929 external database support with uri

pkg/common/client_state.go
Hi guys,
whenever a KeycloakClient is added with:
```
clientAuthenticatorType: client-secret
```
a secret is created with 
```
CLIENT_ID
CLIENT_SECRET
```
But unfortunately the CLIENT_SECRET is always empty and therefore can't be used the way its meant.
Thats fixed within this PR.
Offtopic: Its a pain to create JIRA Ticket ... then Github-Issue .. mark all things with the JIRA-Ticket...
To check it you can adjust:
```
---
kind: KeycloakClient
metadata:
finalizers:
- client.cleanup
generation: 2
name: example-name
namespace: example-ns-name
spec:
client:
bearerOnly: false
clientAuthenticatorType: client-secret
clientId: pay
defaultClientScopes:
- some-scopeshere1
- some-scopeshere2
- some-scopeshere3
description: The nice description
id: exampl-example …
```
=> KEYCLOAK-13008: Set the ClientSecret to be written as CLIENT_SECRET

pkg/model/util.go, pkg/model/util_test.go
The `SanitizeResourceName` function is used to create valid names for `Secret` resources for each `KeycloakUser`. This function doesn't sanitize uppercase letters (not allowed by Kubernetes), therefore if a user has an uppercase letter in their name, the secret will fail to be created:
```yaml
status:
message: >-
Secret "credential-openshift-TEST-redhat-rhmi-rhsso" is invalid:
metadata.name: Invalid value:
"credential-openshift-TEST-redhat-rhmi-rhsso": a DNS-1123 subdomain
must consist of lower case alphanumeric characters, '-' or '.', and must
start and end with an alphanumeric character (e.g. 'example.com', regex used
for validation is
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
phase: failing
```
These changes modify the `SanitizeResourceName` function to …
=> KEYCLOAK-13158 Sanitize uppercase letters from resource name

deploy/cluster_roles/cluster_role.yaml, deploy/role.yaml
The `k8s/client-go` library logic attempts to update an event instead of creating it when it already
exists. However, the operator doesn't have permissions to patch events, so it will fail and
show a "Server rejected event" error log.
Add the `patch` verb to the `""` apiGroup in `deploy/role.yaml` in order to allow the operator
to perform the update.
[KEYCLOAK-13159](https://issues.redhat.com/browse/KEYCLOAK-13159)
Also tracked in the Integreatly board [INTLY-5812](https://issues.redhat.com/browse/INTLY-5812)
* The logic in `k8s/client-go` for deciding when to patch events is based on the `Event.Count` field [1]
* The `operator-sdk` CLI already includes the `patch` verb in the scaffolding for the `role.yaml` file [2]
[1. `k8s/client-go` GitHub …
=> KEYCLOAK-13159 Add `patch` verb to "" apiGroup

pkg/common/client.go, pkg/common/client_test.go, pkg/common/cluster_actions.go, pkg/common/user_state.go, pkg/controller/keycloakuser/keycloakuser_reconciler.go
The `FindUserByUsername` function returns the first user which contains the string specified in the search query. Since this function is used for managing the state of a KeycloakUser, if a KeycloakUser was created or deleted with a username that is a substring of a user that already exists in the realm and is the first result of that query, it will update or delete that user instead.
Example: 
1. `test-admin` already exists in the realm
2. A new KeycloakUser custom resource was created with the username `test`
3. This will update `test-admin` with the `test` user's details.
4. The `test` KeycloakUser custom resource status is set to reconciled.
The following changes ensures that the user found by this function returns the user that matches the correct username. The parameter to the …
=> KEYCLOAK-13018: Ensure state contains the correct user

pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/controller/keycloakclient/keycloakclient_reconciler_test.go
KEYCLOAK-13335
https://issues.redhat.com/browse/KEYCLOAK-13335
Setting directAccessGrantsEnabled in the crd
kind: KeycloakClient
to false has no effect in keycloak.
The Gui show that "Direct Access Grants Enabled" is on.
The reason for that is that the file
keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
has set the property like that:
DirectAccessGrantsEnabled bool `json:"directAccessGrantsEnabled,omitempty"`
If DirectAccessGrantsEnabled is false, then the value is omitted when the client is created via the keycloak api. The keycloak-default value if the value is not specified is true.
1. Create CRD with directAccessGrantsEnabled: False
```
kind: KeycloakClient
metadata:
name: tcm-angular-frontend …
```
=> PR for KEYCLOAK-13335

Makefile
Stumbled across the wrong version number for the operator SDK.
Run `make setup/operator-sdk`
=> Fix wrong version for operator SDK

pkg/model/prometheus_rule.go
https://issues.redhat.com/browse/INTLY-6614
Some discussion in https://issues.redhat.com/browse/INTLY-6614, the gist of which is a review of the critical alerts and if they should be critical (i.e. they page someone when they fire).
My thinking is that only problems that affect a potential service level objective (SLO) should be critical.
In this case, its:
- `KeycloakInstanceNotAvailable` if the service isn't available
- `KeycloakAPIRequestDuration90PercThresholdExceeded` & `KeycloakAPIRequestDuration99.5PercThresholdExceeded` if the service isn't responding as fast as expected
All other alerts would help with debugging & point at potential causes as to why one of the critical alerts are firing, but as long as the SLO is being met, no-one needs to be paged.
1. Install operator in a …
=> Lower alert severity for memory based alerts

pkg/model/prometheus_rule.go
Discussed offline (& in https://issues.redhat.com/browse/INTLY-6614) 
I think it might be best to go down to just 1 critical alert where SRE need to investigate as a matter of urgency at this time i.e. the 'up' alert (KeycloakInstanceNotAvailable).
The response times alerts may become more important in time, but I don't think we know what immediate steps an SRE could take when paged, so i think lowering them to warning is reasonable.
There could be an immediate action to increase the number of instances (in the keycloak CR) while investigation continues, but i'd like to have that discussion with our SRE team first as there's resourcing concerns there. Also, they Keycloak CR gets reset back to 2 in RHMI whenever changed at the moment (David Ffrench is following up on that to allow changes) …
=> Lower severity of rate based alerts

pkg/common/controller_utils.go, pkg/common/controller_utils_test.go
[KEYCLOAK-13743](https://issues.redhat.com/browse/KEYCLOAK-13743)
This Pull Request fixes an error reported in https://github.com/operator-framework/community-operators/pull/1479. The reason Travis failed in the Operatorhub was that `KeycloakBackup` CR was pointing to a non-existing Keycloak cluster.
=> KEYCLOAK-13743 Do not panic on missing Keycloak cluster

pkg/common/cluster_actions.go, pkg/model/keycloak_deployment.go, pkg/model/rhsso_deployment.go
https://issues.redhat.com/browse/KEYCLOAK-13850
While doing a diff of our current fork of the keycloak-operator, there were some changes that have not been brought upstream to this operator which I think have some small benefit.
Each different change is in a separate commit rather than a separate PR but I can do this if it is preferred.
1. Minor text changes
3. Only set external DB env vars when external DB is used
4. Always reconcile the liveness and readiness checks on update the keycloak deployment, the same as is being done on the RHSSO deployment.
=> Small quality of life updates

Makefile
[KEYCLOAK-13634](https://issues.redhat.com/browse/KEYCLOAK-13634)
This Pull Request allows to compile Keycloak Operator against multiple architectures.
=> KEYCLOAK-13634 Support for multiple architectures

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, deploy/crds/keycloak.org_keycloakusers_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakuser_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
Adds attributes field to KeycloakUser CRD.
https://issues.redhat.com/browse/INTLY-6491
The attributes field is missing in KeycloakUser CRD and we want to be able to use this field to flag when users are created in other products in the [RHMI operator](https://github.com/integr8ly/integreatly-operator)
https://www.keycloak.org/docs-api/9.0/rest-api/index.html#_userrepresentation
=> adds attributes field to KeycloakUser CRD

Makefile, deploy/operator.yaml, docs/building.md, test/e2e/constants.go, test/e2e/keycloak_main_test.go
[KEYCLOAK-14016](https://issues.redhat.com/browse/KEYCLOAK-14016)
* Adds `test/e2e-image` make target to execute the tests with operator deployed to the cluster (as opposed to `test/e2e` which executes the operator locally while testing). This uses the `operator-sdk` CLI tool to automatically prepare the environment in a random namespace. From my PoV it doesn't make much sense to run this target in Travis as it uses an operator image and doesn't build and deploy the operator image.
* Fixes `WaitForOperatorDeployment` to use correct CR name.
* Updates docs on how to use ingress with Docker's K8s.
I was not able to get `test/e2e-image` working with Ingress on my local machine. The operator doesn't seem to "communicate" with Ingress when deployed to the container (`test/e2e` works fine). …
=> KEYCLOAK-14016 Support for testing operator as an image

Dockerfile, container.yaml, content_sets.yaml, productize.sh
https://issues.redhat.com/browse/KEYCLOAK-13616
This Pull Request introduces a setup required for building both Keycloak and RHSSO from the same repo. OSBS (which is used by the product) requires additional YAML files (added by this commit). I also introduced `productize.sh` script, which replaces `Dockerfile` with the on prepared specially for OSBS.
=> KEYCLOAK-13616 Setup for the product

README.md, pkg/model/constants.go, pkg/model/database_secret.go, pkg/model/image_manager.go, pkg/model/postgresql_backup.go, pkg/model/postgresql_deployment.go, test/e2e/keycloak_main_test.go
[KEYCLOAK-14075](https://issues.redhat.com/browse/KEYCLOAK-14075)
[KEYCLOAK-13399](https://issues.redhat.com/browse/KEYCLOAK-13399)
As agreed with @iankko and @pdrozd, we need to downgrade Postgresql to 10 for both Keycloak and the product (to be consistent). This also requires upgrading RHMI Backup Container and adding additional Postgresql version in order to use backups.
=> KEYCLOAK-14075 Downgrade to Postgresql 10

deploy/crds/keycloak.org_keycloaks_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/model/keycloak_route.go
[KEYCLOAK-14095](https://issues.redhat.com/browse/KEYCLOAK-14095)
[KEYCLOAK-12307](https://issues.redhat.com/browse/KEYCLOAK-12307)
This Pull Request changes the TLS configuration from Passthrough to Re-encrypt. In addition to that, it introduces a new `tlsTermination` parameter (in the `Keycloak` CR) that can be set to `passthrough` and fall back to previous behavior.
This change improves user experience and sacrifices a bit of security. As we agreed with @stianst, the safest way of running Keycloak is a Passthrough Route that sends all encrypted traffic to Keycloak. However, this option is quite hard to configure as the Signing Operator would need to create a valid, publicly accepted certificate to Keycloak. Much easier option is to configure this on an Ingress or Route. Moreover, …
=> KEYCLOAK-12307 TLS Termination configuration

pkg/model/image_manager.go, pkg/model/image_manager_test.go
[KEYCLOAK-13634](https://issues.redhat.com/browse/KEYCLOAK-13634)
As agreed with @ASzc and @hmlnarik, we introduced a convenient option for overriding all RHSSO images (for both architectures). In such a case, you need to override `RELATED_IMAGE_RHSSO` env. variable.
=> KEYCLOAK-13634 Allow a single RHSSO image override

pkg/model/image_manager.go, pkg/model/image_manager_test.go, pkg/model/init_container_common.go, pkg/model/profile_manager.go, pkg/model/profile_manager_test.go
[KEYCLOAK-14261](https://issues.redhat.com/browse/KEYCLOAK-14261)
This Pull Request introduces a new RHSSO Init Container.
=> KEYCLOAK-14261 Introduce RHSSO Init Container

pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_controller.go
https://issues.redhat.com/browse/KEYCLOAK-14278
During the [ManageSuccess function](https://github.com/keycloak/keycloak-operator/blob/master/pkg/controller/keycloak/keycloak_controller.go#L222-L235) of the keycloak CR controller, the secondary resources are checked to see if they are in a ready state. This is reported in the Keycloak CR status.
The [isResourcesReady function](https://github.com/keycloak/keycloak-operator/blob/master/pkg/common/cluster_state.go#L481) does not take into account if an external database is used and will also report not ready because the postgresql deployment resource doesn't exist.
1. Create a Keycloak CR with externalDatabase enabled
2. Verify the Keycloak CR status reports ready:true and phase:reconciling
=> KEYCLOAK-14278 Fix isResourcesReady postgres deployment

pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/postgresql_service.go
KEYCLOAK-13711
If the attribute POSTGRES_EXTERNAL_ADDRESS in secret keycloak-db-secret is changed from a dns-name to an ip-address or vice-versa, the service keycloak-postgresql is not adapted accordingly.
I discovered this in a setup with an external database.
Keycloak-CRD:
```
kind: Keycloak
metadata:
name: keycloak
labels:
app: sso
test: sso
spec:
instances: 1
extensions:
- https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
externalAccess:
enabled: False
externalDatabase:
enabled: True
podDisruptionBudget:
enabled: True
```
and a secret like this 
```
apiVersion: v1
data:
POSTGRES_DATABASE: cG9zdGdyZXNxbA==
POSTGRES_EXTERNAL_ADDRESS: MS4xLjEuMQ==
POSTGRES_EXTERNAL_PORT: NTQzMg==
POSTGRES_PASSWORD: …
```
=> KEYCLOAK-13711  Change of attribute POSTGRES_EXTERNAL_ADDRESS in secret keycloak-db-secret not handled

set-version.sh
[KEYCLOAK-14316](https://issues.redhat.com/browse/KEYCLOAK-14316)
This Pull Request corrects the path to image override. This is necessary when tagging new images.
Please note, that this is a partial fix for [KEYCLOAK-14316](https://issues.redhat.com/browse/KEYCLOAK-14316). Please do not close the JIRA once this one gets merged.
=> KEYCLOAK-14316 Override proper variable

.github/workflows/go.yml, .github/workflows/lint.yml
This change introduce the usage of GolangCI linter with GH actions
* [Example of GH actions working](https://github.com/arkham-labs/louketo-proxy/actions/runs/98490210)
* Output from the last run against Keycloak Operator repository - https://github.com/abstractj/keycloak-operator/actions/runs/99048680
=> [KEYCLOAK-14083] Run golangci-lint as part of pull request workflow

deploy/crds/keycloak.org_keycloaks_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/controller/keycloakclient/keycloakclient_reconciler_test.go
... when  standardFlowEnabled and publicClient are set to false
KEYCLOAK-14088
KEYCLOAK-14134
I have to create clients that have the fields standardFlowEnabled and publicCLient both set to false.
When the json for the respective keycloak api-call is created, these fields are missing due to the omitempty tag.
But keycloak used the default true for these values so the keycloak client get the wrong defaults.
Current implementation
```
// True if Standard flow is enabled.
// +optional
StandardFlowEnabled bool `json:"standardFlowEnabled,omitempty"`
// True if this is a public Client.
// +optional
PublicClient bool `json:"publicClient,omitempty"`
```
Apply this config:
```
kind: KeycloakClient
metadata:
name: client-test
labels:
app: sso
spec:
realmSelector: …
```
=> Fix generation of keycloak client 

productize.sh
https://issues.redhat.com/browse/KEYCLOAK-14517
There was a commit to fix this in dist-git repo, but container.yaml is rewritten by rsync command.
This is a upstream PR of https://github.com/keycloak/keycloak-operator-prod/pull/4
=> KEYCLOAK-14517 Operator container build needs to reflect $BUILD_OPENJ9

pkg/model/constants.go, pkg/model/postgresql_deployment.go
https://issues.redhat.com/browse/KEYCLOAK-14568
Version of https://github.com/keycloak/keycloak-operator/pull/217 with only one commit. Sorry for any confusion.
=> KEYCLOAK-14568 Moving postgres pv mount path values over to constants.go

pkg/model/rhsso_deployment.go
https://issues.redhat.com/browse/KEYCLOAK-14559
Adding wildcard support for ca-cert configuration. This will allow configuration support for both Vanilla k8 & Openshift as the path varies var/run/secrets/kubernetes.io/serviceaccount/ca.crt (K8s) & /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt (Openshift).
Change is already done for `keycloak_deployment.go`. It was pending for `rhsso_deployment.go` this image release: https://github.com/jboss-container-images/redhat-sso-7-openshift-image/releases/tag/v7.4.0.GA-RHBZ-1813894-fix
https://github.com/jboss-container-images/redhat-sso-7-openshift-image/pull/125
=> KEYCLOAK-14559 updating ca bundle env variable with wildcard ca value

.travis.yml, Makefile, docs/building.md
[KEYCLOAK-14063](https://issues.redhat.com/browse/KEYCLOAK-14063)
Run new `e2e-local-image` Makefile target in a freshly built image deployed in the cluster. Previous `e2e-image` target has been renamed to `e2e-latest-image`.
I had to add timeout settings for Travis because this target is taking longer. Some tests might fail, but I'm not sure if it is due to wrong deployment or the tests themselves. Please share your thoughts.
=> KEYCLOAK-14063. Run e2e tests in a cluster using a fresh image.

.github/workflows/container.yml
When:
- a commit is pushed to any branch,
- or when a commit is tagged
build the Dockerfile located in the repo root, then push it to
https://quay.io/repository/keycloak/keycloak-operator
=> KEYCLOAK-14888 Create container build workflow for Quay

pkg/model/keycloak_deployment.go
Kube-DNS is configured with `ndots: 5`, which means that local names will be iteratively retried with five root names of the FQDN removed.
This fixes clusters that have DNS names other than `cluster.local`.
1. Create a cluster with a specific cluster name such as `c1.example.com`
1. Install Keycloak-Operator, notice operator generates a `Deployment` that has `cluster.local` in it's DNS names. These DNS names are incorrect and the deployment fails.
1. Apply patch and try again. `kube-dns` is configured with `ndots: 5`, which solves the problem.
=> KEYCLOAK-14931: Remove `cluster.local` from DNS names in the deployment genertor.

pkg/model/client_secret.go, pkg/model/database_secret.go, pkg/model/database_secret_test.go, pkg/model/keycloak_admin_secret.go
https://issues.redhat.com/browse/KEYCLOAK-14316
=> KEYCLOAK-14316 Fix "assignment to entry in nil map" error

.gitattributes
All files under the `vendor/` directory, and any file starting with `zz_generated` will be marked as a "generated" file, which GitHub will hide from diffs by default.
See [GitHub's documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-how-changed-files-appear-on-github), [linguist-generated documentation](https://github.com/github/linguist/#generated-code), and [git pattern syntax](https://www.git-scm.com/docs/gitignore#_pattern_format).
=> KEYCLOAK-16060 Hide vendor and generated files from GitHub diffs

pkg/model/keycloak_ingress.go, pkg/model/keycloak_ingress_test.go
Support Spec.TLS override made in Keycloak Ingress after it is originally created. This will help to use keycloak ingress with
other ingress controller deployed in the cluster. It works same way as Spec.Rules[0].Host override is implemented.
https://issues.redhat.com/browse/KEYCLOAK-16079
=> KEYCLOAK-16079 Support Spec.TLS override in Keycloak Ingress

pkg/common/client_state.go, pkg/controller/keycloakclient/keycloakclient_reconciler_test.go, pkg/model/client_secret.go
This fix will update client secret in kubernetes Secret and
keycloak when KeycloakClient CR is updated with new client secret
in Spec instead of resetting back to what is saved in keycloak
https://issues.redhat.com/browse/KEYCLOAK-16102
=> KEYCLOAK-16102 Update client secret on change in KeycloakClient CR

deploy/crds/keycloak.org_keycloaks_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/model/keycloak_ingress.go, pkg/model/keycloak_ingress_test.go, pkg/model/keycloak_route.go, pkg/model/keycloak_route_test.go
Support overriding default host set in Ingress/Route through Keycloak CR
https://issues.redhat.com/browse/KEYCLOAK-15109
=> KEYCLOAK-15109 Ingress/Route Host Override

.github/workflows/ci.yml, Makefile
Replaces the usage of [medyagh/setup-minikube@master](https://github.com/medyagh/setup-minikube)
Unfortunately, the GitHub actions for Minikube still use `add-path` which is deprecated by GitHub and no longer functional. We tried to submit [a pull-request](https://github.com/medyagh/setup-minikube/pull/13) to the author, but we didn't hear anything back until now.
Considering that this is critical, I'd suggest to include the changes in this PR.
* `ACTIONS_ALLOW_UNSECURE_COMMANDS` solves the issue, but it is unsafe.
* Coveralls was intentionally removed as it was already broken a while ago. We may revisit it in the future, but not a priority for now.
* Supersedes #271
=> [KEYCLOAK-16368] CI is broken due to some changes on GitHub actions

pkg/model/prometheus_rule.go
https://issues.redhat.com/browse/KEYCLOAK-16751
There is no action that SRE can take when this alert is firing, and in prod environment it has been fired a lot and generated a lot of false positives.
Another option could be we can increase the time for which the alert will be generated. But again, when the alert is fired, there is no action that SRE can take to solve the issue.
=> fix(alerts): remove the KeycloakJavaNonHeapThresholdExceeded alert

README.md, pkg/model/image_manager.go
https://issues.redhat.com/browse/KEYCLOAK-16766
A new version of the backup-container image has been published. There are no changes that affect the Keycloak operator's usage of it, so this is mostly just a respin on top of an updated base image.
https://quay.io/repository/integreatly/backup-container?tab=tags
=> KEYCLOAK-16766 Bump backup-container image to latest 1.0.16

pkg/common/cluster_state.go, pkg/common/cluster_state_test.go
https://issues.redhat.com/browse/KEYCLOAK-16771
*What:*
On OpenShift, Keycloak CR will be stuck with `status.ready = false` if `.spec.ExternalAccess.enable = false`
*Why:*
Keycloak Operator should not be waiting for the route to become ready if the route is disabled via Keycloak CR spec.
1. Install the operator on a testing Openshift cluster (or run it locally against a namespace on Openshift cluster)
2. Create a valid Keycloak CR with `.spec.ExternalAccess.enable = false`
3. After keycloak StatefulSet and postgres deployment become ready, `.status.ready` field of the CR should become `true`
=> Check route readiness only if ExternalAccess is enabled

pkg/model/postgresql_deployment.go
Launch a init container to fix permissions on PVC.
Fix a problem when launching a Keycloak instance with aws-ebs disk
https://issues.redhat.com/browse/KEYCLOAK-16730
I'm using the Keycloak operator with a Kops cluster deployed in AWS. When I try to deploy a Keycloak instance, the Postgresql instance fail to start with a problem on disk default owner (root).
The only way to fix the problem is to mount this persistent volume, set the owner to postgres (group postgres) and let the postgres container start.
- Create a Kops cluster with aws-ebs storage class
- Launch the operator
- Generate a Keycloak instance
- After a few seconds/minutes the Keycloak postgres must be started
=> Use a init container to set PVC permissions

pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, test/e2e/keycloak_client_test.go
Since the default is true we can only express unset/false/true with a *bool.
See this discussion https://github.com/keycloak/keycloak-operator/pull/121#discussion_r368417642
=> Fix fullScopeAllowed in client CRD

cmd/manager/main.go, pkg/common/auto_detect.go, pkg/k8sutil/k8sutil.go, test/e2e/minikube_issue_3129_workaround.go
Jira: https://issues.redhat.com/browse/MGDAPI-1043
Remove dependency to k8sutil package.
We are upgrading to operator sdk >= 1.x and k8sutils is no longer exposed in these versions. 
I've ran e2e tests against a cluster and everything passed but open to other tests as required. 
Build and deploy from this branch to confirm installation and reconciliation works as expected.
=> MGDAPI-1043 Eliminate k8sutil dependency

go.mod, pkg/common/auto_detect.go, pkg/common/cluster_state.go, pkg/common/controller_utils.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/postgresql_deployment.go
https://issues.redhat.com/browse/KEYCLOAK-16864
Init containers change that was added would work only
with plain Kubernetes. Code changes made to detect if
the underlying cluster is openshift or Kubernetes and then to add the init containers
part based on that.
> create either openshift or kuberntes cluster
> run the operator 
Follow steps here: https://github.com/keycloak/keycloak-operator#local-development for running the operator locally
>  verify that pods are created and running (keycloak and postgresql)
>  Verify that deployment config of postgres doesnt contain initcontainers sections for openshift, but has the same for plain kuberntes
> verify key cloak works fine - sanity check
=> Fix for postgres deployment CR for openshift

pkg/model/keycloak_deployment.go, pkg/model/keycloak_deployment_test.go
Add DB_PORT to Keycloak Deployment for connecting to external
Postgres database running on non-default port
https://issues.redhat.com/browse/KEYCLOAK-16637
=> KEYCLOAK-16637 Add DB_PORT to Keycloak Deployment

pkg/model/rhsso_deployment.go
These are the operator specific changes for rhsso deployment.
Sets the owners count for cache as 2.
JIRA Link: https://issues.redhat.com/browse/MGDSTRM-1659
Sets the owners count for cache as 2.
CACHE_OWNERS_AUTH_SESSIONS_COUNT and CACHE_OWNERS_COUNT are set as 2
=> MGDSTRM-1659 - Use at least two owners for caches

deploy/examples/keycloak/keycloak-with-vault.yaml, deploy/examples/realm/realm_with_ldap.yaml
https://issues.redhat.com/browse/KEYCLOAK-17209
This adds an example for how to configure ldap while storing the bind credential in the plaintext vault via a mounted secret.
=> KEYCLOAK-17209 Add example for configuring ldap

cmd/manager/main.go
KEYCLOAK-13731
Resulting from a user issue, where a client secret was changed through the UI, and not reset to the correct value by the operator in a timely manner.
1. Create a keycloak CR
2. Wait a few minutes without editing the CR
3. See that the operator is reconciling frequently.
=> KEYCLOAK-17371 add default resync period to keycloak-operator

Makefile, README.md
Removed all generalized delete statements including the deletion of PVs from the Makefile cluster/clean command. This approach deletes the resources created by cluster/prepare.
KEYCLOAK-17090
This changes the Documentation in README.md to be more accurate. 
> To clean the cluster (Removes CRDs, CRs, RBAC and namespace)
(It does not specifically delete CRs, but since its CRDs are deleted, the results should be the identical)
Add the steps required to check this change. Following an example.
1. Create a Persistent Volume somewhere in the cluster.
1. `make cluster/prepare`
1. `kubectl apply -f deploy/operator.yaml -f deploy/examples/keycloak/keycloak.yaml`
1. `sleep 120s`
1. `make cluster/clean`
1. `sleep 60s`
1. `kubectl get pv`
1. `kubectl get keycloaks.keycloak.org`
1. `kubectl get pv`
* …
=> Fix Issue KEYCLOAK-17090; Keycloak Operator Deletes all PVs in a Cluster

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, test/e2e/keycloak_realm_test.go
Mimics `displayName` under realm to also allow setting `displayNameHtml`.
1. Create a realm without `displayNameHtml`.
2. Set the value and apply.
3. Verify that the realm was updated as expected.
Tested live and seems to work as expected on Kubernetes, image at `almahmoud/keycloak-operator:displayhtml`
=> KEYCLOAK-17449 Adding displayNameHtml to Realm

pkg/common/client.go, pkg/common/client_test.go
If the sso-x509-https-secret secret is used to provision a server cert for the keycloak to use
then this will be loaded and set in the http client used to communicate
with the Keycloak server. If the env var is not set, then the behaviour is as before, e.g. insecure.
Run the unit test included in the PR. 
`go test -timeout 30s -run ^TestClient_useKeycloakServerCertificate$ github.com/keycloak/keycloak-operator/pkg/common`
- [X ] Automated Tests
=> KEYCLOAK-17675 Allow supplying a server certificate to use when connecting to keycloak

.github/workflows/ci.yml, Makefile, deploy/crds/keycloak.org_keycloaks_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/common/client.go, pkg/controller/keycloak/keycloak_controller.go, pkg/controller/keycloakrealm/keycloakrealm_controller.go, pkg/controller/keycloakuser/keycloakuser_controller.go, test/e2e/keycloak_realm_test.go, test/e2e/keycloaks_test.go
https://issues.redhat.com/browse/KEYCLOAK-16220
https://issues.redhat.com/browse/KEYCLOAK-15895
I'm addressing two issues in a single PR as I believe it makes sense. [KEYCLOAK-15895](https://issues.redhat.com/browse/KEYCLOAK-15895) was blocked by [KEYCLOAK-16220](https://issues.redhat.com/browse/KEYCLOAK-16220) and at the same time [KEYCLOAK-15895](https://issues.redhat.com/browse/KEYCLOAK-15895) verifies that [KEYCLOAK-16220](https://issues.redhat.com/browse/KEYCLOAK-16220) fixed the problem.
=> KEYCLOAK-16220 KEYCLOAK-15895 Operator communicates with KC using external URLs

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, deploy/examples/realm/basic_realm_with_password_policy.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, test/e2e/keycloak_realm_test.go
Setting up a password policy for realms in KeyCLoak is a frequent requirement by the customers. This change allows the realm yaml to specify the password policy for the realm
Run the local setup make code/run
DEfine password policy as per deploy/examples/realm/basic_realm_with_password_policy.yaml
Verify in the relam/authentication left bar of the Keycloak GUI and see;etc the "Passwor dPolicy" tab on the right.
=> Allow Password policy to be defined in the keycloak realm CRD

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, test/e2e/keycloak_realm_test.go
https://issues.redhat.com/browse/KEYCLOAK-18024
Currently its not possible to control the userManagedAccessAllowed property on keycloak realm using the operator. We want to setup a keycloak realm using the operator with UMA enabled, so we would need this setting.
Add the steps required to check this change. Following an example.
1. create a KeycloakRealm custom resources with spec.realm userManagedAccessAllowed set to true
2. wait for the resource to be created in the keycloak server
3. check if UMA allowed setting is enabled on the created realm
=> enable UMA from within the operator

pkg/common/auto_detect.go
KEYCLOAK-18287
Grafana dashboard watch was being created incorrectly. 
Install from this branch and confirm keycloak metrics grafana dashboard gets created.
=> KEYCLOAK-18287 fix grafana dashboard watch

deploy/crds/keycloak.org_keycloaks_crd.yaml, deploy/examples/keycloak/keycloak-with-experimental-settings.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/model/keycloak_deployment.go, pkg/model/keycloak_deployment_test.go
KEYCLOAK-17162: Add Support for ServiceAccount
The  Keycloak StatefulSet currently has the serviceAccountName set to be "default". 
This is sufficient in most cases, but we need to pull the Keycloak Image from a repository that requires an imagePullSecret.
This doesn't work with the "default" ServiceAccount.
As we deploy everything with helm charts, it is very difficult to change the existing "default"-ServiceAccount.
We would like to create a specific ServiceAccount for Keycloak that has the imagePullSecrets set as needed and configure Keycloak to use this Service Account.
This pull request enables this without changing the default behavior if the serviceAccountName is not set.
```
k apply -f -
kind: Keycloak
metadata:
name: example-keycloak
labels:
app: …
```
=> KEYCLOAK-17162: Add Support for ServiceAccount

pkg/common/client.go, pkg/controller/keycloakclient/keycloakclient_reconciler_test.go, pkg/model/client_secret.go, pkg/model/util.go
Signed-off-by: Jonathan Vila <jvilalop@redhat.com>
https://issues.redhat.com/browse/KEYCLOAK-19503
As the ticket says, when you use a clientId including a https url, it will fail as there are some chars not allowed for a K8s resource name
1. make cluster/prepare
2. Run operator from IDE , *from master branch*
2. deploy a keycloak.yaml
3. edit the keycloak CR and delete the annotation "service.alpha.openshift.io/serving-cert-secret-name"
4. delete the x509 secret
5. deploy a keycloakrealm.yaml
6. try to deploy a keycloakclient with clientid "https://whatever?value"  ---> will fail
7. stop the operator on the IDE, and now go to the PR branch, and run it
8. try to deploy a keycloakclient with clientid "https://whatever?value"  ---> will work
=> KEYCLOAK-19503 escape name of the secret for client

README.md
As per https://lists.jboss.org/archives/list/keycloak-user@lists.jboss.org/thread/HXUE2IPVPB2HCD5TS3V6L7VEYQWI5JRZ/ , the user mailing list has moved to google groups in 2019
https://issues.redhat.com/browse/KEYCLOAK-19780
This link should be updated to avoid confusion in those looking to ask questions about how to use the operator
Documentation change only
I've removed the checklist as this is a minor non-code change. If this is the incorrect thing to do, please let me know
=> Updating user mailing list link

deploy/crds/keycloak.org_keycloakclients_crd.yaml, deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, pkg/controller/keycloakclient/keycloakclient_controller.go
Currently you can create custom authentication flows on a realm CRD but you cannot use them in clients.
=> KEYCLOAK-18869 Authentication flow binding overrides

deploy/cluster_roles/cluster_role.yaml
Fixes #461.
- just deployed 15.0.2 and found that this was probably overlooked in https://github.com/keycloak/keycloak-operator/commit/fd5aeeb3a8dbf672d5751a021b9eea34006afaed#diff-dd2b7f73672812f28eaeefd88568f005bc349b4647e015a36b2789ad29b5221fL66
This fixes the apiGroups in the cluster role manifest.
Closes #461
=> Use networking.k8s.io ingress in cluster role

README.md, pkg/model/image_manager.go, set-version.sh
The keycloak-init-container image is currently pinned to the "master"
shared tag, which has not been updated for two years.
This commit updates the image tag to use the latest released tag for the
container.
This container comes with a couple of benefits:
* Accurate URL parsing, the Python parsing has issues.
* Ability to use basic auth URLs for extensions.
* Much smaller image size.
Fixes #478
- Reduce the vulnerabilities from 309 ( 101 High ) to none (https://quay.io/repository/keycloak/keycloak-init-container?tag=latest&tab=tags)
- Allows the use of private extensions via the use of a basic auth URL.
=> KEYCLOAK-17330 Update to latest stable keycloak-init container

pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/apis/keycloak/v1alpha1/util.go, pkg/apis/keycloak/v1alpha1/util_test.go, pkg/common/client_state.go, pkg/common/cluster_actions.go, pkg/controller/keycloakclient/keycloakclient_reconciler.go, pkg/controller/keycloakclient/keycloakclient_reconciler_test.go, pkg/model/client_secret.go, test/e2e/keycloak_client_test.go
Closes #473
- Updated the naming scheme of the kubernetes secrets created by `KeylcoakClient` custom resources to now use the custom resource name (which matches Keycloak documentation) over the previously used `clientID`.
- `KeycloakClient` reconciliation process will create secrets using custom resource name, i.e.`keycloak-client-secret-<custom resource name>`, and also check for existence of secret using the old naming scheme, i.e. `keycloak-client-secret-<clientID>`, and delete appropriately. Put condition in place to avoid cyclical creation/deletion of secrets in case of `client_id == custom_resource_name`.
- Open to suggestions on approach and names used (deprecated was one that came to mind 🤷 )
- Tip of the hat to @imykolenko for their initial work in #361 👍 
See examples to …
=> Fix client secret naming scheme to match docs

set-version.sh
Similar to #465 the keycloak-operator image also needs '-legacy' appended, otherwise it will fail to pull the non-existent 17.0.1
https://quay.io/repository/keycloak/keycloak-operator?tab=tags
Closes #515
=> Update operator image coordinates in set-version.sh

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, test/e2e/keycloak_realm_test.go
Closes https://github.com/keycloak/keycloak-operator/issues/522
Allows for the configuration of changedSyncPeriod for UserFederationProvider
=> #522 Allow config of changedSyncPeriod for Realm.UserFederationProvider

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, test/e2e/keycloak_realm_test.go
Closes https://github.com/keycloak/keycloak-operator/issues/534
1. Run the operator
2. Create a KeycloakRealm resource with a client scope and add that scope to the defaultDefaultClientScopes field on the resource
3. Check that the client scope is listed in the default client scopes list in Keycloak and that, when adding a new client, the scope gets added to its default scopes list.
=> Add defaultDefaultClientScopes field to KeycloakRealm resource
