keycloak/keycloak-operator

.travis.yml
https://issues.jboss.org/browse/INTLY-3358
The goal of this PR is to add a Travis CI file to achieve the following
1. Running the unit tests
2. Running goveralls (This should comment on the PR)
3. On master - build the image and push it to the quay repo
4. On a tag - build the image and push it to the quay repo
Also to have GolangCI setup on the repo to also comment on PRs
=> feat: Add Travis CI (INTLY-3358)

Makefile, go.mod
This Pull Request downgrades Go to 1.12.
=> Downgrade to Go 1.12

Makefile, README.md
https://issues.jboss.org/browse/INTLY-3605
Adding additional make commands and tidying up make file.
Setups CRDs, RBAC and namespace. Does not setup the operator, as this would likely want to be run from a debugger or local launch or possible deploy to the namespace in a cluster
Removes, CRDs, RBAC and namespace
Creates example CRs
=> feat: Adding operator install and uninstall commands

.gitignore, .travis.yml, Makefile
Follows up on https://github.com/keycloak/keycloak-operator/pull/25
=> Updates for [KEYCLOAK-11498] Add Coveralls to CI

.golangci.yml, deploy/examples/keycloak/keycloak.yaml, go.mod, go.sum, pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/constants.go, pkg/model/grafana_dashboard.go, pkg/model/keycloak/constants.go, pkg/model/keycloak_service.go, pkg/model/postgresql_deployment.go, pkg/model/postgresql_persistent_volume_claim.go, pkg/model/postgresql_service.go, pkg/model/prometheus_rule.go, pkg/model/rhsso/constants.go, pkg/model/service_monitor.go
[INTLY-3351](https://issues.jboss.org/browse/INTLY-3351)
[INTLY-3355](https://issues.jboss.org/browse/INTLY-3355)
[INTLY-3356](https://issues.jboss.org/browse/INTLY-3356)
This Pull Request adds reconciliation loop to the database (Postgresql) resources, including:
* PVC
* Service
*Deployment
I verified this by running it on Minikube.
As you can probably see, the implementation is very verbose. However, the type checking works really well and it is very hard to put things in wrong places. Once we have all the resources there, we can think about optimizing code.
A side note - this Pull Request doesn't contain any logic for checking if DB is running. I noticed that we used wrong environmental variables previously (in RHSSO templates) and that could potentially cause problems when deploying …
=> INTLY-3356 INTLY-3355 INTLY-3351 Postgresql deployment

.golangci.yml, pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/constants.go, pkg/model/database_secret.go, pkg/model/keycloak_deployment.go, pkg/model/keycloak_discovery_service.go, pkg/model/keycloak_service.go, pkg/model/postgresql_deployment.go, pkg/model/util.go
[https://issues.jboss.org/browse/INTLY-3609](INTLY-3609)
[https://issues.jboss.org/browse/INTLY-3610](INTLY-3610)
[https://issues.jboss.org/browse/INTLY-3352](INTLY-3352)
[https://issues.jboss.org/browse/INTLY-3354](INTLY-3354)
This Pull Request adds reconciliation loop to:
* Keycloak deployment
* Database secret
* Keycloak discovery service
=> Intly 3610 intly 3354 reconcile db secret and keycloak deployment

build/Dockerfile, build/tools/build-operator.sh
* Initial tests done with quay.io here: https://quay.io/repository/abstractj/keycloak-operator/build/5f8fccb5-9640-46b4-ac44-6f858b9d55a6
=> [KEYCLOAK-11536] Keycloak Operator Dockerfile fails to build

pkg/model/keycloak_deployment.go
[INTLY-3225](https://issues.jboss.org/browse/INTLY-3225)
This PR configures Keycloak to use OpenShift generated certificates for HTTPS. This way, other services may trust Keycloak by using `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`.
=> INTLY-3225 Use OpenShift certificate if possible

pkg/common/auto_detect.go, pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_controller.go
None
Adding secondary watches for all secondary resources of the Keycloak CR
None
=> feat: Setup watches for secondary resources

README.md, deploy/crds/Keycloak.yaml, deploy/examples/keycloak/rhsso.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/common/cluster_state.go, pkg/common/state_manager.go, pkg/controller/keycloak/keycloak_controller.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/constants.go, pkg/model/grafana_dashboard.go, pkg/model/rhsso_deployment.go
[INTLY-3765](https://issues.jboss.org/browse/INTLY-3765)
This Pull Request adds support for RHSSO by using a program argument - `--profile RHSSO`.
=> INTLY-3765 RHSSO deployment

pkg/model/constants.go
[INTLY-3765](https://issues.jboss.org/browse/INTLY-3765)
We decided to pin Red Hat SSO image down.
=> INTLY-3765 Pin RHSSO image down

.golangci.yml
This Pull Request disables `wsl` linter
=> Disable WSL linter

.gitignore, .travis.yml, Makefile, go.mod, go.sum, test/e2e/keycloak_test.go, test/e2e/utils.go
[INTLY-3766](https://issues.jboss.org/browse/INTLY-3766)
This Pull Request introduces fully functional end to end tests using Minikube on Travis. Please note, that we need to aggregate 2 coverage files in order to get proper results. This is why we're using `gover` project.
=> INTLY-3766 End to end tests

Makefile
[KEYCLOAK-11533](https://issues.jboss.org/browse/KEYCLOAK-11533)
@abstractj I had your ticket "under my knife". I hope you don't mine me implementing this :)
=> KEYCLOAK-11533 Autoformat code using Goimports

deploy/crds/Keycloak.yaml, deploy/crds/KeycloakRealm.yaml
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields
=> feat: enable pruning in the CRDs to prevent storing unknown fields in etcd

deploy/examples/keycloak/keycloak.yaml, deploy/examples/keycloak/rhsso.yaml, deploy/examples/realm/realm_with_users.yaml, go.mod, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/controller/keycloakrealm/keycloakrealm_controller.go, pkg/model/constants.go, pkg/model/init_container_common.go, pkg/model/keycloak_admin_secret.go, pkg/model/keycloak_deployment.go, pkg/model/monitoring_constants.go, pkg/model/rhsso_deployment.go
INTLY-3606
Allow installing extensions through the Keycloak CR
1. Deploy keycloak or rhsso using the provided example CRs
2. Test the metrics endpoint under `<base url>/auth/realms/master/metrics`
3. Edit one of the Realm examples and add `eventsListeners: ["metrics-listener"]` to the spec
4. Create the realm and log in to it
5. Make sure the realm login event is recorded
=> add init container

pkg/model/keycloak_deployment.go
Restoring a line deleted by a mistake here: https://github.com/keycloak/keycloak-operator/pull/60/files#diff-ae3bc997be08b0c72ba9b14bab077a2cL200
=> Fix number of replicas in Keycloak deployment

cmd/manager/main.go
https://issues.jboss.org/browse/INTLY-3228
Adding the monitoring-key to the service monitor created by the operator so it is picked up by the middleware monitoring stack
1. Run `make cluster/prepare`
2. Run `oc label namespace keycloak  monitoring-key=middleware`
2. Setup application monitoring stack in the cluster
2. Change operator image in `operator.yml` to `quay.io/davidffrench/keycloak-operator:INTLY-3228`
3. Deploy operator to keycloak namespace
4. Run `kubectl apply -f deploy/examples/keycloak/keycloak.yaml
5. Verify from prometheus that the `controller_runtime_reconcile_` metrics are returned
=> feat: Add monitoring-key to operator servicemonitor

pkg/model/postgresql_backup.go
This Pull Request allows to print out backup (as text) in Pod logs. This is very convenient for testing.
=> Make backup visible in the logs

README.md
None
Docs updates before release
=> fix: Updating docs

deploy/olm-catalog/keycloak-operator/7.0.1/keycloak-operator.7.0.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/keycloak-operator.package.yaml
Aligned version. Will need to retag.
=> Fix version

build/Dockerfile, build/tools/build-operator.sh
This Pull Request adds some debugging information to the build process.
=> Add more debug information for the build

deploy/olm-catalog/keycloak-operator/7.0.1/keycloak-operator.7.0.1.clusterserviceversion.yaml
=> OLM manifest fixes

pkg/model/rhsso_deployment.go
None
Have rhsso statefulset take replicas from spec into account
=> fix: Allow rhsso deployment to take into account replicas from spec

build/Dockerfile
=> Workaround for Quay builds

pkg/controller/keycloak/keycloak_reconciler_test.go
[KEYCLOAK-12250](https://issues.jboss.org/browse/KEYCLOAK-12250)
=> KEYCLOAK-12250 Travis test fix

pkg/model/postgresql_deployment.go
[KEYCLOAK-12275](https://issues.jboss.org/browse/KEYCLOAK-12275)
=> KEYCLOAK-12275 Fix Postgresql mount paths

CONTRIBUTING.md, README.md, docs/building.md
In order to disabel GH issues, we first need to provide information to the community on how to contribute and report issues. These changes are pretty much based on the changes from other repositories.
Could you please take a look when you get the chance?
=> [KEYCLOAK-12332] Include into the README file the same information from the main repository

set-version.sh
[KEYCLOAK-12056](https://issues.jboss.org/browse/KEYCLOAK-12056)
This Pull Request integrates Keycloak Operator with @stianst release pipeline. We decided that we no need `release.sh`.
=> KEYCLOAK-12056 Set Version script

deploy/role.yaml
[INTLY-4129](http://issues.jboss.org/browse/INTLY-4129)
Note, that I reused the original JIRA as it should be implemented there in the first place.
This is a necessary change for the `8.0.1` release. Without it, the Operator complains on insufficient permissions and won't scan the `Keycloak` CRs. We need this for both, `master` branch and `8.0.1` tag. Other bits work as expected.
//cc @davidkirwan @stianst @abstractj
=> [INTLY-4129] add necessary permission

docs/README.asciidoc
No Jira ID - updated documentation README.asciidoc
Check out docs/README.asciidoc
=> docs - updated README.asciidoc with additional info + link to keycloak docs

deploy/olm-catalog/keycloak-operator/7.0.1/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.1/keycloak-operator.8.0.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/8.0.1/keycloak.org_keycloakbackups_crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.1/keycloak.org_keycloakclients_crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.1/keycloak.org_keycloakrealms_crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.1/keycloak.org_keycloaks_crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.1/keycloak.org_keycloakusers_crd.yaml, deploy/olm-catalog/keycloak-operator/keycloak.package.yaml
[KEYCLOAK-12623](https://issues.redhat.com/browse/KEYCLOAK-12623)
This Pull Request synchronizes OLM information with:
* https://github.com/operator-framework/community-operators/pull/1087
* https://github.com/operator-framework/community-operators/pull/1088
=> KEYCLOAK-12623 8.0.1 OLM descriptor

README.md
`README.md` contains broken links.
=> README.md: fix broken links

pkg/model/constants.go, pkg/model/pod_monitor.go, pkg/model/prometheus_rule.go, pkg/model/service_monitor.go
https://issues.redhat.com/browse/INTLY-5027
Check the alerts here: https://prometheus-route-rhmi-middleware-monitoring.apps.weili-43.w3g9.s1.devshift.org/alerts. You should see alerts for 2 instances of keycloak are working
=> fix an few issues discovered when test monitoring

.golangci.yml, pkg/model/constants.go, pkg/model/database_secret.go, pkg/model/keycloak_admin_secret.go, pkg/model/util.go
[KEYCLOAK-13013](https://issues.redhat.com/browse/KEYCLOAK-13013)
=> KEYCLOAK-13013 Extend charset in passwords

deploy/operator.yaml, pkg/model/constants.go, version/version.go
Please push this commit into a newly created `8.0.2` branch (once Travis is happy).
=> 8.0.2 Release

deploy/olm-catalog/keycloak-operator/8.0.2/keycloak-operator.8.0.2.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/8.0.2/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.2/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.2/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.2/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/8.0.2/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/keycloak.package.yaml
This is a sync commit with the Operatorhub. Please merge this one after two PRs against the Operatorhub get in:
* https://github.com/operator-framework/community-operators/pull/1247
* https://github.com/operator-framework/community-operators/pull/1246
=> Sync with Operatorhub

deploy/operator.yaml, pkg/model/constants.go, version/version.go
=> Keycloak Operator 9.0.0

deploy/olm-catalog/keycloak-operator/9.0.0/keycloak-operator.9.0.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/9.0.0/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/9.0.0/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/9.0.0/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/9.0.0/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/9.0.0/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/keycloak.package.yaml
=> Operatorhub sync for 9.0.0

deploy/operator.yaml, pkg/model/constants.go, version/version.go
Keycloak Operator 9.0.2 Release
=> Keycloak Operator 9.0.2

pkg/model/constants.go
[KEYCLOAK-13909](https://issues.redhat.com/browse/KEYCLOAK-13909)
I did some manual 7.3 -> 7.4 migration tests and it works better than I expected. I tried adding some operator created resources (realm/client/users) and also some manual entities and it worked perfectly.
=> KEYCLOAK-13909 Change default RHSSO image to 7.4

.travis.yml, Makefile, docs/building.md, hack/issue_3129_workaround.yaml, hack/modify_etc_hosts.sh, pkg/controller/keycloak/keycloak_controller.go, pkg/model/constants.go, pkg/model/keycloak_ingress.go, test/e2e/constants.go, test/e2e/keycloak_test.go, test/e2e/utils.go
[KEYCLOAK-13580](https://issues.redhat.com/browse/KEYCLOAK-13580)
This Pull Request fixes Ingress with TLS support and tests it in the e2e tests.
=> KEYCLOAK-13580 Ingress Tests

pkg/controller/keycloak/keycloak_migrations.go
=> KEYCLOAK-14035 Fix migration bug

README.md
This corrects the environment variable names for externalized images and add the RELATED_ prefix.
=> [KEYCLOAK-14133] Correct manual for externalized images

test/e2e/constants.go, test/e2e/keycloak_main_test.go, test/e2e/keycloak_user_test.go, test/e2e/utils.go
=> KEYCLOAK-14068 Test coverage for UserCRD

Dockerfile, productize.sh
=> KEYCLOAK-13616 Update productization script

Dockerfile, productize.sh
https://issues.redhat.com/browse/KEYCLOAK-13616
During the productization process we found out that UBI8 with Golang module doesn't really work in Koji. We decided to use the same builder as the OpenShift Team does.
The test image is available at: `docker pull docker.io/slaskawi/keycloak-operator`.
The `Dockerfile` after productization looks like the following:
```
FROM openshift/golang-builder:1.13 AS build-env
RUN git clone --single-branch --branch master https://github.com/keycloak/keycloak-operator.git .  #aaf0377d882ff4f2efb2aac026f0b600581715a3
COPY . /src/
RUN cd /src && \
make code/compile && \
echo "Build SHA1: $(git rev-parse HEAD)" &&
{ echo "$(git rev-parse HEAD)" } > /src/BUILD_INFO
FROM ubi8-minimal:8-released
LABEL …
```
=> KEYCLOAK-13616 Use better builder image

Dockerfile
Fixed a small mistake in `Dockerfile`. Otherwise it threw an error when performing `docker build`.
//cc @ASzc @hmlnarik
=> KEYCLOAK-13616 Fixed build error

test/e2e/constants.go, test/e2e/keycloak_client_test.go, test/e2e/keycloak_main_test.go, test/e2e/utils.go
=> KEYCLOAK-14068 Test coverage for ClientCRD

pkg/common/client_state.go, pkg/common/cluster_actions.go, pkg/controller/keycloakclient/keycloakclient_controller.go, test/e2e/constants.go
[KEYCLOAK-14187](https://issues.redhat.com/browse/KEYCLOAK-14187)
This Pull Request enabled Keycloak to generate `ClientID` and syncs it back to the CR.
=> KEYCLOAK-14187 Generated ClientID fix

productize.sh
[KEYCLOAK-13616](https://issues.redhat.com/browse/KEYCLOAK-13616)
Changed the package name to tech preview.
=> KEYCLOAK-13616 Use Tech Preview package

productize.sh
This Pull Request introduces changes necessary for Delivery Repos.
=> KEYCLOAK-13616 Update for delivery repos

Makefile
https://issues.redhat.com/browse/KEYCLOAK-14367
=> KEYCLOAK-14367 Fix Operator SDK development command

pkg/controller/keycloakbackup/keycloakbackup_controller.go, pkg/controller/keycloakclient/keycloakclient_controller.go, pkg/controller/keycloakrealm/keycloakrealm_controller.go, pkg/controller/keycloakuser/keycloakuser_controller.go
https://issues.redhat.com/browse/KEYCLOAK-14409
Unified variable names introduced in https://github.com/keycloak/keycloak-operator/pull/208
=> KEYCLOAK-14409 Unify variable names

pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/model/keycloak_deployment.go, pkg/model/util_test.go
https://issues.redhat.com/browse/KEYCLOAK-13394
This Pull Request adds proper proxy settings and moves one test to the correct place.
=> KEYCLOAK-13394 Add proxy settings

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/commit-message.yml
https://issues.redhat.com/browse/KEYCLOAK-14519
=> KEYCLOAK-14519 Development template and automation improvements

pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/common/cluster_actions.go, pkg/controller/keycloakclient/keycloakrclient_reconciler.go
https://issues.redhat.com/browse/KEYCLOAK-13112
=> KEYCLOAK-13112 Fixed client generation error and ImplicitFlow

productize.sh
Needed for keycloak/keycloak-pipeline#291
=> KEYCLOAK-14590 Update productize.sh for exploded sources

deploy/crds/keycloak.org_keycloakbackups_crd.yaml, deploy/crds/keycloak.org_keycloaks_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/keycloakbackup_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, pkg/common/cluster_state.go, pkg/controller/keycloak/keycloak_migrations.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/model/postgresql_backup_persistent_volume_claim.go, pkg/model/postgresql_persistent_volume_claim.go
[KEYCLOAK-14327](https://issues.redhat.com/browse/KEYCLOAK-14327)
=> KEYCLOAK-14327 Allow user to specify storage class

pkg/controller/keycloak/keycloak_controller.go
https://issues.redhat.com/browse/KEYCLOAK-13234
This PR always sets the correct version to the `status` field.
=> KEYCLOAK-13234 Always set version to Keycloak CR Status

pkg/model/image_manager.go
https://issues.redhat.com/browse/KEYCLOAK-14697
=> KEYCLOAK-14697 Fix RHSSO Init container image

pkg/common/backup_state.go
[KEYCLOAK-14572](https://issues.redhat.com/browse/KEYCLOAK-14572)
=> KEYCLOAK-14572-fix the Backup state inconsistent

pkg/model/keycloak_deployment.go
https://issues.redhat.com/browse/KEYCLOAK-14814
see JIRA description
=> explicit set the FailureThreshold for the readiness and liveness probes

pkg/model/image_manager.go
https://issues.redhat.com/browse/KEYCLOAK-15161
The switch statements in Go require a bit different structure. See [this link](https://yourbasic.org/golang/switch-statement/).
=> KEYCLOAK-15161 Fix switch statement to avoid panic

deploy/kustomization.yaml, deploy/namespace.yaml, kustomization.yaml
https://issues.redhat.com/browse/KEYCLOAK-15446
=> KEYCLOAK-15446 Adding kustomize

Makefile
https://issues.redhat.com/browse/KEYCLOAK-15713
Go tests doesn't use vendor by default. This Pull Request makes it to do so.
The `operator-sdk test` calls don't require adding `-mod=vendor`. They do it automatically, here's a line I obtained when debugging it on Travis (see [here](https://travis-ci.com/github/keycloak/keycloak-operator/jobs/390385411)):
```
Running e2e local tests:
operator-sdk test local --go-test-flags "-tags=integration -coverpkg ./... -coverprofile cover-e2e.coverprofile -covermode=count -timeout 0 -mod=vendor" --operator-namespace default --up-local --debug --verbose ./test/e2e
DEBU[0000] Debug logging is set                         
INFO[0000] Testing operator locally.                    
DEBU[0000] Running []string{"go", "test", "-mod=vendor", "./test/e2e/...", …
```
=> KEYCLOAK-15713 Use vendor directory for tests

Makefile, README.md
=> KEYCLOAK-14955 Support for running operator tests without admin permissions

productize.sh
=> KEYCLOAK-16039 Build Init Container fails on bad image repo parsing

Dockerfile, productize.sh
https://issues.redhat.com/browse/KEYCLOAK-15516
See https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.2&container-tabs=gti&gti-tabs=unauthenticated
=> KEYCLOAK-15516 Update the image to UBI 8.2

container.yaml
=> Add ppc64le platform to container.yaml

deploy/crds/keycloak.org_keycloaks_crd.yaml
Fix description in CRD to match with the one in type
https://issues.redhat.com/browse/KEYCLOAK-15109
Fix description mismatch with the comment in type
=> KEYCLOAK-15109 Fix CRD description

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
KEYCLOAK-16227
Once this pull request is as you want it I can prepare the remaining ones in a similar way.
Add the steps required to check this change. Following an example.
1. Add some of changed options in the example realm
2. `kubectl apply` the realm
3. Open Admin Console
4. Check if the options are set correctly
=> KEYCLOAK-16227 - Add realm login settings to realm CRD

Makefile, README.md, deploy/examples/monitoring/federation.yaml, pkg/model/grafana_dashboard.go, pkg/model/monitoring_constants.go
https://issues.redhat.com/browse/KEYCLOAK-16058
https://issues.redhat.com/browse/KEYCLOAK-16057
This Pull Request revisits the Keycloak Dashboard and brings automatic Application Monitoring Operator installation to our Makefile.
=> KEYCLOAK-16057 KEYCLOAK-16058 Use the latest AMO version

deploy/crds/keycloak.org_keycloaks_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/controller/keycloak/keycloak_controller.go, pkg/controller/keycloak/keycloak_migrations.go, pkg/controller/keycloak/keycloak_migrations_test.go, test/assert/asserts.go
KEYCLOAK-15955
https://github.com/keycloak/keycloak-documentation/pull/1062
I'll add the docs once I've got the confirmation this is the right approach. ;)
=> KEYCLOAK-15955 Implement a pluggable Upgrade strategy

pkg/common/client.go
https://issues.redhat.com/browse/KEYCLOAK-16523
Update httpTransport to maintain proxy settings for http requests.
=> KEYCLOAK-16523 Respect proxy settings

Makefile
https://issues.redhat.com/browse/KEYCLOAK-16058
https://issues.redhat.com/browse/KEYCLOAK-16057
=> KEYCLOAK-16057 KEYCLOAK-16058 Fixed wrong path

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
https://issues.redhat.com/browse/KEYCLOAK-16611
This prevents a warning while running make code/gen.
https://github.com/kubernetes/kube-openapi/blob/master/pkg/idl/listtype_test.go
=> [KEYCLOAK-16611] Add listType to realm/RedirectorIdentityProviderOverride

README.md
I followed the link every now and then to learn about the progress of this promising project. But had to manually click around until I remembered again how to and what for I need to filter to only see the Keycloak Operator specific issues.
=> Link to Keycloak Operator specific JIRA issues

deploy/olm-catalog/keycloak-operator/12.0.1/keycloak-operator.v12.0.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/12.0.1/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.1/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.1/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.1/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.1/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/ci.yaml, deploy/olm-catalog/keycloak-operator/keycloak.package.yaml
This is just a sync commit. Please merge it after this 2 PRs get in:
- https://github.com/operator-framework/community-operators/pull/2940
- https://github.com/operator-framework/community-operators/pull/2941
=> Keycloak Operator 12.0.1 Operatorhub sync

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, test/e2e/keycloak_realm_test.go
https://issues.redhat.com/browse/KEYCLOAK-16359
This pull request is only intended for the last commit, the others are minor fixes to code generation etc. that should be done beforehand.
I will rebase as needed.
=> KEYCLOAK-16359 Add realm email settings to realm CRD

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, test/e2e/keycloak_realm_test.go
https://issues.redhat.com/browse/KEYCLOAK-16360
This pull request is only intended for the last commit, the others are minor fixes to code generation etc. that should be done beforehand.
I will rebase as needed.
=> KEYCLOAK-16360 Add realm theme settings to realm CRD

pkg/model/image_manager.go, version/version.go
https://issues.redhat.com/browse/KEYCLOAK-15254
=> KEYCLOAK-15254 Use master or latest images for development

pkg/model/grafana_dashboard.go
KEYCLOAK-17131
We need to reflect the changes that were recently introduced to the Graphana operator.
See: https://github.com/integr8ly/grafana-operator/pull/344
=> KEYCLOAK-17131 Remove spec.name from Grafana Dashboard

pkg/model/keycloak_ingress.go, test/e2e/keycloaks_test.go
https://issues.redhat.com/browse/KEYCLOAK-16406
=> KEYCLOAK-16406 Hide metrics endpoint in Ingress

deploy/olm-catalog/keycloak-operator/12.0.3/keycloak-operator.v12.0.3.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/12.0.3/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.3/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.3/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.3/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/12.0.3/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/keycloak.package.yaml
This is just a sync commit. Please merge it after this 2 PRs get in:
* https://github.com/operator-framework/community-operators/pull/3163
* https://github.com/operator-framework/community-operators/pull/3162
=> Keycloak Operator 12.0.3 Operatorhub sync

pkg/model/rhsso_deployment.go
https://issues.redhat.com/browse/KEYCLOAK-17240
Please merge this PR after https://github.com/jboss-container-images/redhat-sso-7-openshift-image/pull/173/files
=> KEYCLOAK-17240 Enable metrics for RHSSO deployment

Makefile, cmd/manager/main.go, go.mod, pkg/common/auto_detect.go, pkg/common/cluster_state.go, pkg/common/controller_utils.go, pkg/controller/controller.go, pkg/controller/keycloak/keycloak_controller.go, pkg/controller/keycloak/keycloak_reconciler.go, pkg/controller/keycloak/keycloak_reconciler_test.go, pkg/controller/keycloakbackup/keycloakbackup_controller.go, pkg/controller/keycloakclient/keycloakclient_controller.go, pkg/controller/keycloakrealm/keycloakrealm_controller.go, pkg/controller/keycloakuser/keycloakuser_controller.go, pkg/model/constants.go, pkg/model/keycloak_deployment.go, pkg/model/keycloak_monitoring_service.go, pkg/model/monitoring_constants.go, pkg/model/service_monitor.go
https://issues.redhat.com/browse/KEYCLOAK-16548
This Pull Request creates additional Service for gathering Wildfly metrics. However, the most important change is to the Dashboard. Here's how it looks now [link](https://snapshot.raintank.io/dashboard/snapshot/fcIxz4Iu6qwuVhI3EU3JcgUtS2bWmvrU). Note, that some graphs didn't render correctly because RHSSO doesn't provide any way to enable metrics (we probably need to implement it - checking with @iankko).
=> KEYCLOAK-16548 Collect more Keycloak metrics

deploy/cluster_roles/cluster_role.yaml, deploy/crds/keycloak.org_keycloaks_crd.yaml, deploy/role.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/controller/keycloak/keycloak_controller.go, pkg/model/keycloak_route.go, pkg/model/keycloak_route_test.go
https://issues.redhat.com/browse/KEYCLOAK-17177
For more information, please see the comments in https://issues.redhat.com/browse/KEYCLOAK-17177
=> KEYCLOAK-17177 Add custom host permissions

.github/workflows/ci.yml, Makefile
https://issues.redhat.com/browse/KEYCLOAK-17436
This PR fixes the CI
=> KEYCLOAK-17436 Move kube config between root and runner users

Dockerfile, productize.sh
https://issues.redhat.com/browse/KEYCLOAK-17613
=> KEYCLOAK-17613 Change the builder image coordinates

.github/workflows/ci.yml
https://issues.redhat.com/browse/KEYCLOAK-17647
=> KEYCLOAK-17647 Make Minikube version configurable

deploy/olm-catalog/keycloak-operator/13.0.0/keycloak-operator.v13.0.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/13.0.0/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/13.0.0/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/13.0.0/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/13.0.0/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/13.0.0/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/keycloak.package.yaml
This is just a sync commit. Please merge it after this 2 PRs get in:
* https://github.com/operator-framework/community-operators/pull/3767
* https://github.com/operator-framework/community-operators/pull/3766
=> Keycloak Operator 13.0.0 Operatorhub sync

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, deploy/crds/keycloak.org_keycloaks_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloak_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
https://issues.redhat.com/browse/KEYCLOAK-18092
=> KEYCLOAK-18092 Upgrade to 13.0.0 failing because of status.externalURL field

deploy/olm-catalog/keycloak-operator/15.0.0/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/15.0.0/manifests/keycloak-operator.v15.0.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/15.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.0/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.0/metadata/annotations.yaml, deploy/olm-catalog/keycloak-operator/15.0.1/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/15.0.1/manifests/keycloak-operator.v15.0.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/15.0.1/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.1/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.1/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.1/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.1/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.1/metadata/annotations.yaml
This PR syncs OperatorHub releases.
* 15.0.0
* https://github.com/k8s-operatorhub/community-operators/pull/104
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/93
* 15.0.1
* https://github.com/k8s-operatorhub/community-operators/pull/106
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/96
=> Keycloak Operator 15 Operatorhub sync

deploy/olm-catalog/keycloak-operator/15.0.2/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/15.0.2/manifests/keycloak-operator.v15.0.2.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/15.0.2/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.2/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.2/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.2/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.2/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.0.2/metadata/annotations.yaml
Added label for the realm example to allow all-default CR creation
Signed-off-by: Jonathan Vila <jvilalop@redhat.com>
KEYCLOAK-19101
1. create a test catalog bundle to install this test operator ( from the deploy/olm-catalog/keycloak-operator/15.0.2 folder )
```bash
docker build -f bundle.Dockerfile -t keycloak-operator-bundle:1502 .
docker tag keycloak-operator-bundle:1502 quay.io/{your account}/keycloak-operator-bundle:1502
docker push quay.io/{your account}/keycloak-operator-bundle:1502
~/{your path to operator-registry project}/operator-registry/bin/opm index add --bundles quay.io/{your account}/keycloak-operator-bundle:1502 \
--tag quay.io/{your account}/keycloak-operator-test-catalog:1502 --container-tool docker --from-index quay.io/openshift-community-operators/catalog:latest …
```
=> KEYCLOAK-19101 Added new version folder 15.0.2 for the OLM deploy

deploy/olm-catalog/keycloak-operator/ci.yaml
Related PRs:
* https://github.com/k8s-operatorhub/community-operators/pull/142
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/146
=> KEYCLOAK-19107 Update OperatorHub reviewers

pkg/common/client.go, pkg/controller/keycloakclient/keycloakclient_controller.go, pkg/controller/keycloakrealm/keycloakrealm_controller.go, pkg/controller/keycloakuser/keycloakuser_controller.go, test/e2e/keycloaks_test.go, test/e2e/utils.go
All fixes are related (failing only on OpenShift), therefore I'm keeping it as one PR.
=> KEYCLOAK-19134 KEYCLOAK-19154 KEYCLOAK-19165 E2E tests fixes

pkg/controller/keycloakrealm/keycloakrealm_reconciler.go
=> KEYCLOAK-18867 change getDesiredUserSate to getDesiredUserState

README.md
=> KEYCLOAK-19061 doc: add reference to KeycloakUser CRD

pkg/controller/keycloakclient/keycloakclient_reconciler_test.go, pkg/model/client_secret.go
https://issues.redhat.com/browse/KEYCLOAK-19774
=> Keycloak 19774 fix secret name

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/commit-message.yml, CONTRIBUTING.md, README.md
=> #402 Reflect migration from JIRA to GH Issues in the repo

.github/workflows/commit-message.yml, pkg/controller/keycloakbackup/keycloakbackup_controller.go, pkg/model/keycloak_deployment.go, pkg/model/rhsso_deployment.go, test/e2e/keycloaks_test.go, test/e2e/utils.go
Signed-off-by: Jonathan Vila <jvilalop@redhat.com>
KEYCLOAK-19819 - GH #404
=> KEYCLOAK-19819 #404 - setting podlabels in reconcile

deploy/olm-catalog/keycloak-operator/15.1.0/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/15.1.0/manifests/keycloak-operator.v15.1.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/15.1.0/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.0/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.0/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.0/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.0/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.0/metadata/annotations.yaml
#415
Closes #415 
To generate structure to add to the PR to publish in OperatorHub.io
1. Build bundle and test catalog
2. deploy it in OCP
3. search for keycloak operator in operators , check it comes from test catalog
4. install it
5. check keycloak version is 15.1.0
=> Create OLM structure for 15.1.0

deploy/olm-catalog/keycloak-operator/15.1.1/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloak-operator.v15.1.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/metadata/annotations.yaml
#420
Closes #420
New KC version that needs the new version of the Operator
=> Create OLM structure for 15.1.1

deploy/olm-catalog/keycloak-operator/15.1.1/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloak-operator.v15.1.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/15.1.1/metadata/annotations.yaml, deploy/olm-catalog/keycloak-operator/16.0.0/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/16.0.0/manifests/keycloak-operator.v16.0.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/16.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.0.0/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.0.0/metadata/annotations.yaml
Closes #423 
Creating structure for KC 16.0.0 in OLM
Removing default extension in the CSV as the aerogear is giving problems with KC 16
=> Olm 16.0.0

set-version.sh
Closes #464
Needs to be merged before KC 17.0.0 release!
=> Update legacy image coordinates in set-version.sh

deploy/olm-catalog/keycloak-operator/16.1.0/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/16.1.0/manifests/keycloak-operator.v16.1.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/16.1.0/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.1.0/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.1.0/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.1.0/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.1.0/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/16.1.0/metadata/annotations.yaml
Closes #425 
New 16.1.0 of the Keycloak needs a new Operator
Deploy / Upgrade the operator from the Openshift Marketplace ( test catalog )
Check that it starts and the console opens fine.
=> OLM 16.1.0

pkg/model/image_manager.go
Closes #463
Needs to be merged after KC 17.0.0 release!
=> Update legacy image coordinates in the image manager

deploy/olm-catalog/keycloak-operator/17.0.0/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/17.0.0/manifests/keycloak-operator.v17.0.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/17.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.0/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.0/metadata/annotations.yaml
Closes #486
Signed-off-by: Jonathan Vila <jvilalop@redhat.com>
Closes
=> OLM structure for 17.0.0

deploy/olm-catalog/keycloak-operator/17.0.1/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/17.0.1/manifests/keycloak-operator.v17.0.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/17.0.1/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.1/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.1/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.1/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.1/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/17.0.1/metadata/annotations.yaml
Related PRs:
* https://github.com/k8s-operatorhub/community-operators/pull/962
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/993
Resolves: #510
=> OLM release 17.0.1

deploy/olm-catalog/keycloak-operator/18.0.0/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/18.0.0/manifests/keycloak-operator.v18.0.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/18.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.0/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.0/metadata/annotations.yaml
Catalog PRs:
* https://github.com/k8s-operatorhub/community-operators/pull/1090
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1116
Closes #538
=> OLM release 18.0.0

deploy/crds/keycloak.org_keycloakclients_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakclient_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/common/client.go, pkg/common/client_state.go, pkg/common/user_state.go, pkg/controller/keycloakclient/keycloakclient_controller.go, pkg/controller/keycloakclient/keycloakclient_reconciler.go, pkg/controller/keycloakuser/keycloakuser_reconciler.go, test/e2e/keycloak_client_test.go
=> Service Account Roles Configuration

deploy/crds/keycloak.org_keycloakrealms_crd.yaml, pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go, pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go, test/e2e/keycloak_realm_test.go
Closes #532 
Adds the OTP fields to the CRD
=> Added OTP fields to CRD

deploy/olm-catalog/keycloak-operator/18.0.1/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/18.0.1/manifests/keycloak-operator.v18.0.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/18.0.1/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.1/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.1/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.1/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.1/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.1/metadata/annotations.yaml
Catalog PRs:
* https://github.com/k8s-operatorhub/community-operators/pull/1341
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1306
Closes #555
=> OLM release 18.0.1

deploy/olm-catalog/keycloak-operator/18.0.2/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/18.0.2/manifests/keycloak-operator.v18.0.2.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/18.0.2/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.2/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.2/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.2/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.2/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/18.0.2/metadata/annotations.yaml
Closes #564
Related PRs:
* https://github.com/k8s-operatorhub/community-operators/pull/1400
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1356
=> OLM release 18.0.2

deploy/cluster_roles/cluster_role.yaml, deploy/role.yaml, pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go, pkg/controller/keycloak/keycloak_migrations.go, pkg/controller/keycloak/keycloak_migrations_test.go, pkg/model/keycloak_deployment.go, pkg/model/rhsso_deployment.go, test/assert/asserts.go, test/e2e/keycloak_main_test.go, test/e2e/keycloaks_test.go, test/e2e/testing_parameters.go
=> Operator cannot reconcile StatefulSet if Selector is misconfigured

pkg/model/keycloak_deployment.go, pkg/model/keycloak_deployment_test.go, pkg/model/rhsso_deployment.go, pkg/model/rhsso_deployment_test.go
=> RH-SSO Deployment doesn't reflect serviceAccountName

deploy/olm-catalog/keycloak-operator/19.0.0/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/19.0.0/manifests/keycloak-operator.v19.0.0.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/19.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.0/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.0/metadata/annotations.yaml
Closes #574
Related PRs:
* https://github.com/k8s-operatorhub/community-operators/pull/1527
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1462
=> OLM release 19.0.0

deploy/olm-catalog/keycloak-operator/19.0.1/bundle.Dockerfile, deploy/olm-catalog/keycloak-operator/19.0.1/manifests/keycloak-operator.v19.0.1.clusterserviceversion.yaml, deploy/olm-catalog/keycloak-operator/19.0.1/manifests/keycloakbackups.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.1/manifests/keycloakclients.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.1/manifests/keycloakrealms.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.1/manifests/keycloaks.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.1/manifests/keycloakusers.keycloak.org.crd.yaml, deploy/olm-catalog/keycloak-operator/19.0.1/metadata/annotations.yaml
Closes #576 
Related PRs:
* https://github.com/k8s-operatorhub/community-operators/pull/1552
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1493
=> OLM release 19.0.1
